--TEMPORARILY CREATED SO THAT THE FOREIGN KEY CONSTRAINT WORKS.
--YOU CAN DROP THEM AND MODIFY THEM TO CREATE THE FINAL TABLES.
--==========
--CREATE TABLE Member (memberId INTEGER PRIMARY KEY AUTOINCREMENT);
--CREATE TABLE MembershipPlan (planId INTEGER PRIMARY KEY AUTOINCREMENT);
--CREATE TABLE Class (classId INTEGER PRIMARY KEY AUTOINCREMENT);

CREATE TABLE GymFacility (
	gymId INTEGER PRIMARY KEY AUTOINCREMENT,
	location VARCHAR(100),
	phone VARCHAR(50),
	manager VARCHAR(50)
);

CREATE TABLE Payment (
	paymentId INTEGER PRIMARY KEY AUTOINCREMENT,
	memberId INTEGER,
	planId INTEGER,
	amountPaid REAL NOT NULL,
	paymentDate DATE NOT NULL,
	
	FOREIGN KEY (memberId) REFERENCES Member,
	FOREIGN KEY (planId) REFERENCES MembershipPlan
);

CREATE TABLE Attends (
	memberId INTEGER NOT NULL,
	classId INTEGER NOT NULL,
	attendanceDate DATE NOT NULL,
	
	PRIMARY KEY (memberId, classId, attendanceDate),
	FOREIGN KEY (memberId) REFERENCES Member,
	FOREIGN KEY (classId) REFERENCES Class
);